# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/wily64"
  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "./provisioning/ansible/playbook.yml"
    #ansible.inventory_path = "./provisioning/ansible/hosts"
    #ansible.verbose = "v"
    #ansible.sudo = true
  end
  
  config.vm.define "develop-vm" do |master|
    #master.vm.hostname = "develop-vm"
    master.vm.network "forwarded_port", guest: 80, host: 8081
    master.vm.network "forwarded_port", guest: 8080, host: 8080
    config.vm.network "private_network", ip: "172.16.16.10", virtualbox__intnet: "intnet"      
  end

  config.vm.provider "virtualbox" do |v|
    v.memory = 1024
    v.cpus = 4
  end
end